### PR TITLE
Implement the calendar tracker feature

### LINKED ISSUE #3: Implement the Calendar Tracker Feature
## Overview:
We need to implement the complete calendar tracker for the 2-day Habit rule. So basically, when a user completes the task (he/she is building habit for) he/she will mark it on the day. This should be saved/updated locally and should be retrieved whenever the app runs. This helps user to keep track and stay motivated to be consistent.

## Requirements:
1. The **2-Day Habit** fragment has a calendar you need to add a button which on clicked prompts a message (for surety, as this can't be change once marked). Upon confirmation mark this day as done.
2. Save this data in local storage and be sure it is able to be retrieved upon running the app anytime.
3. Use beautiful UI elements for marked days, you may implement a new calendar i.e. omit the current calendar style or can create new styles for the existing.
4. Also, make sure user can only mark the same day's date not before or after.
5. Also, **gray out** the upcoming dates (i.e. all the coming dates including the next day).
6. Additionally, you can add any more required intuitive feature as required!

## Importance of this feature:
This feature allows users to keep track of their past accomplishment to build habit and motivates them to be consistent.

## Additional Notes:
- Ensure code is clean and follows Android best practices.
- Feel free to ask questions if you need further clarification or assistance.

### PR DESCRIPTION
**Pull request by RITIK-CHAUDHRY**
## Description

Implement the calendar tracker feature

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #3 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Screenshots (if appropriate):

https://github.com/user-attachments/assets/33f644e8-7e42-4597-897e-3eefb7744405

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Comment by RITIK-CHAUDHRY** [comment]
@mukul-dev please review my pr

**Comment by mukul-dev** [comment]
> @mukul-dev please review my pr

image

Seems like some resource is missing ... I think the URI resource is unable to fetch ... Did you encounter similar error? I tried many a solutions from stackoverflow but none worked..! If you solved this error do share the method.. I am trying for it too but not getting how it can be resolved!

**Comment by RITIK-CHAUDHRY** [comment]
@mukul-dev sir previously because i have worked on issue #4 my repo also contain that part as that files have bugs so when you are checking that files showing error. to resolve this error you open your repo and change only 3 files that i have changed and make local.properties acc to your sdk location of the system. then attaching device with usb debugging on will showcase the same results as of mine.

**Comment by RITIK-CHAUDHRY** [comment]
@mukul-dev the changes i have done to achieve this is fragment2day.java, 2day.xml in reslayout and in res values styles.xml.......just take these files of mine and then run it'll run..

**Comment by mukul-dev** [comment]
Great work @RITIK-CHAUDHRY ! Your code is working close to expected but the main part is still missing the days marked are not yet visible on the calendar.. Implement it as if a day is marked (whether streak is alive or broken) it should bhi visible on the calendar! Additionally, the UI for showing the streak count needs to be pleasing! So you can improve that and keep it just above the calendar! 
Make these changes so that the feature requirements as of now can be fulfilled! Also, for merging this if you can remove the changes you've done in other files regarding other issues, it will be easier or else I can just push your changes to the repo and accept your PR then on the portal! Let me know what you choose to do! 👍👍

**Comment by RITIK-CHAUDHRY** [comment]
@mukul-dev sir to mark the date we have to integrate the MaterialCalendarView library to achieve the desired functionality of highlighting the selected dates with a dark red circle. sir

**Pull request merged**
