### PR TITLE
splash screen added and ui updated and timer bug fixed

### PR DESCRIPTION
**Pull request by adityapratap2005**
## Description

Added a new activity for splash screen and new xml file
used handler in SplashActivity.java to make the splash screen last long for 2 sec and then move to mainactivity
theme updated new appealing colors
both for light and dark mode
added the ui of toolbar for switching theme(only ui)
transition added to fragment change
animation added to button for showing click

FIXED BUG OF TIMER - earlier if timer is working and you click it starts flickering
resolved it and made the timer for 2 minutes

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Related Issue

FIXED BUG OF TIMER - earlier if timer is working and you click it starts flickering
resolved it and made the timer for 2 minutes

Fixes # (issue)#1
(issue)#5
(issue)#2

## Type of change

- [ x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Motivation and Context

The addition of splash screen makes the user experience better and new theme added

## How Has This Been Tested?

since the app is small i added the feature and ran the app in a physical device of Android version 12

## Screenshots (if appropriate):
splash screen
WhatsApp Image 2024-10-11 at 1 13 11 PM 

dark mode:

light mode:

toolbar menu:(only ui currently not functional)

## Checklist:

- [ x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x ] My code follows the code style of this project.
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:Galaxy A21S
* Toolchain:
* SDK:Android SDK 28

### CODE REVIEW

**Comment by mukul-dev** [comment]
@Crisonel Great use of "Handler.postDelayed" for the delay! However, consider using other possible methods for implementing this feature like you can create a different activity set it as entry point of app and then move to the **MainActivity**. Also setting theme inside **oncreate()** method may cause flickering... 
I tested this code in two phones natively and results were quite different, and I tried adding delay of 3 seconds, 5 seconds or so but it was not reflected upon running... so now you try to solve these issues!
Also, you can check out more resources for adding basic animations for logo (a simple zoom in/ zoom out), anything you like about it... for some bonus points too...
Overall, I appreciate your work, but it could be better... you have time left still, so you can get back with a better solution!

**Comment by adityapratap2005** [comment]
@mukul-dev 
Please check my PR for issue 1 and 5 for github

**Comment by mukul-dev** [comment]
> @mukul-dev Please check my PR for issue 1 and 5 for github

Yes i reviewed and accepted for the first issue! The second is regarding UI so its still opened as it can be improved.. few things that i viewed as of now is ... The Tab bar on the top of fragments is not uniform in the two implemented fragments in one of them is centred and in other its at bottom (the text specifically) so that need to be improved.. in the calendar selected date is circled dark purple and text is dark too so you can try out experimentally with more appealing color combinations!

**Comment by adityapratap2005** [comment]
> > @mukul-dev Please check my PR for issue 1 and 5 for github
> 
> Yes i reviewed and accepted for the first issue! The second is regarding UI so its still opened as it can be improved.. few things that i viewed as of now is ... The Tab bar on the top of fragments is not uniform in the two implemented fragments in one of them is centred and in other its at bottom (the text specifically) so that need to be improved.. in the calendar selected date is circled dark purple and text is dark too so you can try out experimentally with more appealing color combinations!

@mukul-dev i have changed the color scheme for light mode
added a toolbar menu for changing theme (only ui)
fixed the timer bug earlier if you press start while the timer is running it would flicker now it does not flicker and timer runs smoothly, also now it runs for 2 min.
adjusted the toolbar text and height problem
instead of creating it in each fragment i created it in activitiy_main.xml and updating it with the java code

Please review my PR for issue (issue)#5 as well as (issue)#2 and the timer bug that i resolved

**Comment by mukul-dev** [comment]
> @mukul-dev i have changed the color scheme for light mode added a toolbar menu for changing theme (only ui) fixed the timer bug earlier if you press start while the timer is running it would flicker now it does not flicker and timer runs smoothly, also now it runs for 2 min. adjusted the toolbar text and height problem instead of creating it in each fragment i created it in activitiy_main.xml and updating it with the java code
> 
> Please review my PR for issue (issue)#5 as well as (issue)#2 and the timer bug that i resolved

The UI is much better, 2 min Timer also is working good (it has something that will be raised as a new issue but for now its working as expected!), Smartly set the toolbar too text too, I am merging this! 

Can you mention what changes do we see upon clicking Light mode/ dark mode in the menu so that i can review and raise issue (if any) afterwards..

**Comment by adityapratap2005** [comment]
@mukul-dev I didn't get the time to make them functional and it was also not required in issue it was optional feature.
Currently they do not function 

Objective is to
If you click on light mode theme will be changed to light
And if you click on dark mode so it changes to dark theme.

**Comment by mukul-dev** [comment]
Yes, it was optional! Make a PR regarding the bug #2 on the portal so that it can be closed, and points can be allotted. Keep up the good work 👍

**Pull request merged**
